// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjJCceBUVtTunX9P3sDLg44z9kIiofhk',
    appId: '1:585195373764:web:41222d5e06ba32d237f591',
    messagingSenderId: '585195373764',
    projectId: 'fir-url-2e8f9',
    authDomain: 'fir-url-2e8f9.firebaseapp.com',
    storageBucket: 'fir-url-2e8f9.firebasestorage.app',
    measurementId: 'G-Q85KZ0CXDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLGKJ5aiE39p4zTVrdIieUzTacgmSEZU',
    appId: '1:585195373764:android:01e6003fa0850b7137f591',
    messagingSenderId: '585195373764',
    projectId: 'fir-url-2e8f9',
    storageBucket: 'fir-url-2e8f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6PnyzzBtXqFfZeTSUSsBrjoSDXtaws0',
    appId: '1:585195373764:ios:4737273b6872cada37f591',
    messagingSenderId: '585195373764',
    projectId: 'fir-url-2e8f9',
    storageBucket: 'fir-url-2e8f9.firebasestorage.app',
    iosBundleId: 'com.example.secureurl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6PnyzzBtXqFfZeTSUSsBrjoSDXtaws0',
    appId: '1:585195373764:ios:4737273b6872cada37f591',
    messagingSenderId: '585195373764',
    projectId: 'fir-url-2e8f9',
    storageBucket: 'fir-url-2e8f9.firebasestorage.app',
    iosBundleId: 'com.example.secureurl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxjJCceBUVtTunX9P3sDLg44z9kIiofhk',
    appId: '1:585195373764:web:c5da97c873c17c2a37f591',
    messagingSenderId: '585195373764',
    projectId: 'fir-url-2e8f9',
    authDomain: 'fir-url-2e8f9.firebaseapp.com',
    storageBucket: 'fir-url-2e8f9.firebasestorage.app',
    measurementId: 'G-D3HNPE0QCM',
  );
}
